use crate::player::Player;

pub struct Property {
    property_type: PropertyType,
    index: u8,
    owner: Option<Player>,
    status: PropertyState,
    num_houses: u8,
}

impl Property {
    pub fn new(index: usize) -> Self {
        Property {
            property_type: PROPERTY_DETAILS[index].property_type,
            index: index as u8,
            owner: None,
            status: PropertyState::Unowned,
            num_houses: 0,
        }
    }

    fn get_details(&self) -> &PropertyDetails {
        &PROPERTY_DETAILS[self.index as usize]
    }

    pub fn take_ownership(&mut self, player: Player) {
        self.owner = Some(player);
    }

    pub fn get_owner(&self) -> Option<&Player> {
        self.owner.as_ref()
    }

    fn is_owner(&self, player: &Player) -> bool {
        match &self.owner {
            Some(owner) => {
                owner.get_name() == player.get_name()
                    && owner.get_position() == player.get_position()
                    && owner.get_money() == player.get_money()
            }
            None => false,
        }
    }

    pub fn get_rent(&self) -> i32 {
        let details = self.get_details();
        if details.house_cost == -1 {
            return details.base_rent;
        }
        match self.num_houses {
            0 => details.base_rent,
            1 => details.single_house_rent,
            2 => details.double_house_rent,
            3 => details.triple_house_rent,
            4 => details.four_house_rent,
            5 => details.hotel_rent,
            _ => -1,
        }
    }

    pub fn build_house(&mut self) {
        if self.get_details().house_cost == -1 {
            println!("Cannot build houses on {}.", self.get_details().name);
            return;
        }
        if self.num_houses < 5 {
            self.num_houses += 1;
        }
    }

    pub fn get_status(&self) -> &PropertyState {
        &self.status
    }
}

#[derive(Copy, Clone)]
pub enum ColorGroup {
    Brown,
    LightBlue,
    Pink,
    Orange,
    Red,
    Yellow,
    Green,
    DarkBlue,
}
#[derive(Copy, Clone)]
pub enum PropertyType {
    Go,
    Standard,
    Railroad,
    Utility,
    Jail,
    FreeParking,
    GoToJail,
    CommunityChest,
    Chance,
    Tax,
}

pub enum PropertyState {
    Unowned,
    Owned,
    NonPurchasable,
}

struct PropertyDetails {
    name: &'static str,
    property_type: PropertyType,
    color_group: Option<ColorGroup>,
    index: u8,
    price: i32,
    base_rent: i32,
    single_house_rent: i32,
    double_house_rent: i32,
    triple_house_rent: i32,
    four_house_rent: i32,
    hotel_rent: i32,
    house_cost: i32,
}

// Define the details for all 40 properties on the board
const PROPERTY_DETAILS: [PropertyDetails; 40] = [
    PropertyDetails {
        name: "Go",
        property_type: PropertyType::Go,
        color_group: None,
        index: 0,
        price: -1,
        base_rent: -1,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Mediterranean Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Brown),
        index: 1,
        price: 60,
        base_rent: 2,
        single_house_rent: 10,
        double_house_rent: 30,
        triple_house_rent: 90,
        four_house_rent: 160,
        hotel_rent: 250,
        house_cost: 50,
    },
    PropertyDetails {
        name: "Community Chest",
        property_type: PropertyType::CommunityChest,
        color_group: None,
        index: 2,
        price: -1,
        base_rent: -1,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Baltic Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Brown),
        index: 3,
        price: 60,
        base_rent: 4,
        single_house_rent: 20,
        double_house_rent: 60,
        triple_house_rent: 180,
        four_house_rent: 320,
        hotel_rent: 450,
        house_cost: 50,
    },
    PropertyDetails {
        name: "Income Tax",
        property_type: PropertyType::Tax,
        color_group: None,
        index: 4,
        price: -1,
        base_rent: 200,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Reading Railroad",
        property_type: PropertyType::Railroad,
        color_group: None,
        index: 5,
        price: 200,
        base_rent: 25,
        single_house_rent: 0,
        double_house_rent: 0,
        triple_house_rent: 0,
        four_house_rent: 0,
        hotel_rent: 0,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Oriental Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::LightBlue),
        index: 6,
        price: 100,
        base_rent: 6,
        single_house_rent: 30,
        double_house_rent: 90,
        triple_house_rent: 270,
        four_house_rent: 400,
        hotel_rent: 550,
        house_cost: 50,
    },
    PropertyDetails {
        name: "Chance",
        property_type: PropertyType::Chance,
        color_group: None,
        index: 7,
        price: -1,
        base_rent: -1,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Vermont Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::LightBlue),
        index: 8,
        price: 100,
        base_rent: 6,
        single_house_rent: 30,
        double_house_rent: 90,
        triple_house_rent: 270,
        four_house_rent: 400,
        hotel_rent: 550,
        house_cost: 50,
    },
    PropertyDetails {
        name: "Connecticut Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::LightBlue),
        index: 9,
        price: 120,
        base_rent: 8,
        single_house_rent: 40,
        double_house_rent: 100,
        triple_house_rent: 300,
        four_house_rent: 450,
        hotel_rent: 600,
        house_cost: 50,
    },
    PropertyDetails {
        name: "Jail",
        property_type: PropertyType::Jail,
        color_group: None,
        index: 10,
        price: -1,
        base_rent: -1,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "St. Charles Place",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Pink),
        index: 11,
        price: 140,
        base_rent: 10,
        single_house_rent: 50,
        double_house_rent: 150,
        triple_house_rent: 450,
        four_house_rent: 625,
        hotel_rent: 750,
        house_cost: 100,
    },
    PropertyDetails {
        name: "Electric Company",
        property_type: PropertyType::Utility,
        color_group: None,
        index: 12,
        price: 150,
        base_rent: 0,
        single_house_rent: 0,
        double_house_rent: 0,
        triple_house_rent: 0,
        four_house_rent: 0,
        hotel_rent: 0,
        house_cost: -1,
    },
    PropertyDetails {
        name: "States Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Pink),
        index: 13,
        price: 140,
        base_rent: 10,
        single_house_rent: 50,
        double_house_rent: 150,
        triple_house_rent: 450,
        four_house_rent: 625,
        hotel_rent: 750,
        house_cost: 100,
    },
    PropertyDetails {
        name: "Virginia Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Pink),
        index: 14,
        price: 160,
        base_rent: 12,
        single_house_rent: 60,
        double_house_rent: 180,
        triple_house_rent: 500,
        four_house_rent: 700,
        hotel_rent: 900,
        house_cost: 100,
    },
    PropertyDetails {
        name: "Pennsylvania Railroad",
        property_type: PropertyType::Railroad,
        color_group: None,
        index: 15,
        price: 200,
        base_rent: 25,
        single_house_rent: 0,
        double_house_rent: 0,
        triple_house_rent: 0,
        four_house_rent: 0,
        hotel_rent: 0,
        house_cost: -1,
    },
    PropertyDetails {
        name: "St. James Place",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Orange),
        index: 16,
        price: 180,
        base_rent: 14,
        single_house_rent: 70,
        double_house_rent: 200,
        triple_house_rent: 550,
        four_house_rent: 750,
        hotel_rent: 950,
        house_cost: 100,
    },
    PropertyDetails {
        name: "Community Chest",
        property_type: PropertyType::CommunityChest,
        color_group: None,
        index: 17,
        price: -1,
        base_rent: -1,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Tennessee Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Orange),
        index: 18,
        price: 180,
        base_rent: 14,
        single_house_rent: 70,
        double_house_rent: 200,
        triple_house_rent: 550,
        four_house_rent: 750,
        hotel_rent: 950,
        house_cost: 100,
    },
    PropertyDetails {
        name: "New York Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Orange),
        index: 19,
        price: 200,
        base_rent: 16,
        single_house_rent: 80,
        double_house_rent: 220,
        triple_house_rent: 600,
        four_house_rent: 800,
        hotel_rent: 1000,
        house_cost: 100,
    },
    PropertyDetails {
        name: "Free Parking",
        property_type: PropertyType::FreeParking,
        color_group: None,
        index: 20,
        price: -1,
        base_rent: -1,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Kentucky Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Red),
        index: 21,
        price: 220,
        base_rent: 18,
        single_house_rent: 90,
        double_house_rent: 250,
        triple_house_rent: 700,
        four_house_rent: 875,
        hotel_rent: 1050,
        house_cost: 150,
    },
    PropertyDetails {
        name: "Chance",
        property_type: PropertyType::Chance,
        color_group: None,
        index: 22,
        price: -1,
        base_rent: -1,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Indiana Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Red),
        index: 23,
        price: 220,
        base_rent: 18,
        single_house_rent: 90,
        double_house_rent: 250,
        triple_house_rent: 700,
        four_house_rent: 875,
        hotel_rent: 1050,
        house_cost: 150,
    },
    PropertyDetails {
        name: "Illinois Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Red),
        index: 24,
        price: 240,
        base_rent: 20,
        single_house_rent: 100,
        double_house_rent: 300,
        triple_house_rent: 750,
        four_house_rent: 925,
        hotel_rent: 1100,
        house_cost: 150,
    },
    PropertyDetails {
        name: "B. & O. Railroad",
        property_type: PropertyType::Railroad,
        color_group: None,
        index: 25,
        price: 200,
        base_rent: 25,
        single_house_rent: 0,
        double_house_rent: 0,
        triple_house_rent: 0,
        four_house_rent: 0,
        hotel_rent: 0,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Atlantic Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Yellow),
        index: 26,
        price: 260,
        base_rent: 22,
        single_house_rent: 110,
        double_house_rent: 330,
        triple_house_rent: 800,
        four_house_rent: 975,
        hotel_rent: 1150,
        house_cost: 150,
    },
    PropertyDetails {
        name: "Ventnor Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Yellow),
        index: 27,
        price: 260,
        base_rent: 22,
        single_house_rent: 110,
        double_house_rent: 330,
        triple_house_rent: 800,
        four_house_rent: 975,
        hotel_rent: 1150,
        house_cost: 150,
    },
    PropertyDetails {
        name: "Water Works",
        property_type: PropertyType::Utility,
        color_group: None,
        index: 28,
        price: 150,
        base_rent: 0,
        single_house_rent: 0,
        double_house_rent: 0,
        triple_house_rent: 0,
        four_house_rent: 0,
        hotel_rent: 0,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Marvin Gardens",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Yellow),
        index: 29,
        price: 280,
        base_rent: 24,
        single_house_rent: 120,
        double_house_rent: 360,
        triple_house_rent: 850,
        four_house_rent: 1025,
        hotel_rent: 1200,
        house_cost: 150,
    },
    PropertyDetails {
        name: "Go To Jail",
        property_type: PropertyType::GoToJail,
        color_group: None,
        index: 30,
        price: -1,
        base_rent: -1,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Pacific Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Green),
        index: 31,
        price: 300,
        base_rent: 26,
        single_house_rent: 130,
        double_house_rent: 390,
        triple_house_rent: 900,
        four_house_rent: 1100,
        hotel_rent: 1275,
        house_cost: 200,
    },
    PropertyDetails {
        name: "North Carolina Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Green),
        index: 32,
        price: 300,
        base_rent: 26,
        single_house_rent: 130,
        double_house_rent: 390,
        triple_house_rent: 900,
        four_house_rent: 1100,
        hotel_rent: 1275,
        house_cost: 200,
    },
    PropertyDetails {
        name: "Community Chest",
        property_type: PropertyType::CommunityChest,
        color_group: None,
        index: 33,
        price: -1,
        base_rent: -1,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Pennsylvania Avenue",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::Green),
        index: 34,
        price: 320,
        base_rent: 28,
        single_house_rent: 150,
        double_house_rent: 450,
        triple_house_rent: 1000,
        four_house_rent: 1200,
        hotel_rent: 1400,
        house_cost: 200,
    },
    PropertyDetails {
        name: "Short Line",
        property_type: PropertyType::Railroad,
        color_group: None,
        index: 35,
        price: 200,
        base_rent: 25,
        single_house_rent: 0,
        double_house_rent: 0,
        triple_house_rent: 0,
        four_house_rent: 0,
        hotel_rent: 0,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Chance",
        property_type: PropertyType::Chance,
        color_group: None,
        index: 36,
        price: -1,
        base_rent: -1,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Park Place",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::DarkBlue),
        index: 37,
        price: 350,
        base_rent: 35,
        single_house_rent: 175,
        double_house_rent: 500,
        triple_house_rent: 1100,
        four_house_rent: 1300,
        hotel_rent: 1500,
        house_cost: 200,
    },
    PropertyDetails {
        name: "Luxury Tax",
        property_type: PropertyType::Tax,
        color_group: None,
        index: 38,
        price: -1,
        base_rent: 100,
        single_house_rent: -1,
        double_house_rent: -1,
        triple_house_rent: -1,
        four_house_rent: -1,
        hotel_rent: -1,
        house_cost: -1,
    },
    PropertyDetails {
        name: "Boardwalk",
        property_type: PropertyType::Standard,
        color_group: Some(ColorGroup::DarkBlue),
        index: 39,
        price: 400,
        base_rent: 50,
        single_house_rent: 200,
        double_house_rent: 600,
        triple_house_rent: 1400,
        four_house_rent: 1700,
        hotel_rent: 2000,
        house_cost: 200,
    },
];
